#============== netty config =====================================
server:
  address: 192.168.206.146
  port: "8092"

#============== logging ==========================================


#============== spring boot admin web server config and JPA config ==============
spring:
  boot:
    admin:
      client:
        url: http://192.168.206.146:9080/
        username: admin
        password: 1245
        instance:
          management-url: http://192.168.206.146:8092/actuator
          health-url: http://192.168.206.146:8092/actuator/health
          service-url: http://192.168.206.146:8092/
  application:
    name: CDCService
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


#============== spring actuator config ==========================
management:
  endpoints:
    web:
      exposure:
        include: auditevents, beans, caches, conditions, configprops, env, flyway, health, httptrace, info, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: false
      graphite:
        enabled: false
    distribution:
      percentiles-histogram:
        "[http.server.requests]": false

#============== spring hibernate & JPA config ==========================


#============== spring source ms sql NSI datasource ==========================
nsi:
  spring:
    datasource:
      pool-name: nsiDataSource
      username: kobra_main
      password: Ggv123
      url: jdbc:sqlserver://srvr153;databaseName=NSI
      jdbc-url: jdbc:sqlserver://srvr153;databaseName=NSI
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      properties:
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto: none

#============== spring source postgre UFD datasource ==========================
postgre-nsi:
  spring:
    datasource:
      pool-name: ufdDataSource
      username: sa
      #username: akraev1982
      password: Gf07031990
      #password: Kraev12345678
      url: jdbc:postgresql://localhost:5432/nsi
      #url: jdbc:postgresql://pg2.sweb.ru/akraev1982
      jdbc-url: jdbc:postgresql://localhost:5432/nsi
      #jdbcUrl: jdbc:postgresql://pg2.sweb.ru/akraev1982
      driver-class-name: org.postgresql.Driver